SET PAGESIZE 0
SET FEEDBACK OFF
SET HEADING OFF
SELECT 'APARTADOS|' || COUNT(*) FROM APARTADOS;
SELECT 'CAJA_CONFIG|' || COUNT(*) FROM CAJA_CONFIG;
SELECT 'CORTES_CAJA|' || COUNT(*) FROM CORTES_CAJA;
SELECT 'ENTRADAS|' || COUNT(*) FROM ENTRADAS;
SELECT 'INVERSION_ITEMS|' || COUNT(*) FROM INVERSION_ITEMS;
SELECT 'MARGEN_CONFIG|' || COUNT(*) FROM MARGEN_CONFIG;
SELECT 'MOVIMIENTOS_CAJA|' || COUNT(*) FROM MOVIMIENTOS_CAJA;
SELECT 'PERSONAS|' || COUNT(*) FROM PERSONAS;
SELECT 'PRECIOS_HISTORICOS|' || COUNT(*) FROM PRECIOS_HISTORICOS;
SELECT 'PRODUCCIONES|' || COUNT(*) FROM PRODUCCIONES;
SELECT 'PRODUCTOS|' || COUNT(*) FROM PRODUCTOS;
SELECT 'TRASPASOS|' || COUNT(*) FROM TRASPASOS;
SELECT 'TRASPASO_ABONOS|' || COUNT(*) FROM TRASPASO_ABONOS;
SELECT 'TRASPASO_LINEAS|' || COUNT(*) FROM TRASPASO_LINEAS;
SELECT 'VENTAS|' || COUNT(*) FROM VENTAS;
