#!/usr/bin/env python3
"""Import full_dump.json into ATP productos_limpieza schema."""
import json, os, re, shutil, tempfile, datetime
from decimal import Decimal

HOME = os.path.expanduser("~")
WALLET_SRC = os.path.join(HOME, "productos-limpieza", "wallet")
DUMP = os.environ.get("PL_DUMP", os.path.join(HOME, "productos-limpieza", "_migrate", "full_dump.json"))
USER = os.environ.get("PL_DB_USER", "productos_limpieza")
PASSWORD = os.environ["PL_DB_PASSWORD"]
DSN = os.environ.get("PL_DB_DSN", "cgatodb_tp")

# Parents before children
ORDER = [
    "PRODUCTOS", "PERSONAS", "CAJA_CONFIG", "MARGEN_CONFIG",
    "ENTRADAS", "PRODUCCIONES", "VENTAS", "APARTADOS",
    "TRASPASOS", "TRASPASO_LINEAS", "TRASPASO_ABONOS",
    "MOVIMIENTOS_CAJA", "CORTES_CAJA", "INVERSION_ITEMS", "PRECIOS_HISTORICOS",
]

def prepare_wallet():
    tmp = tempfile.mkdtemp(prefix="pl_imp_wallet_")
    for name in os.listdir(WALLET_SRC):
        src = os.path.join(WALLET_SRC, name)
        if not os.path.isfile(src):
            continue
        # Keep pem for oracledb 4; JDBC path preferred if this fails
        shutil.copy2(src, os.path.join(tmp, name))
    sqlnet = os.path.join(tmp, "sqlnet.ora")
    if os.path.exists(sqlnet):
        text = open(sqlnet, "r", encoding="utf-8").read()
        text = re.sub(r'DIRECTORY\s*=\s*"[^"]*"', f'DIRECTORY="{tmp}"', text, flags=re.I)
        open(sqlnet, "w", encoding="utf-8").write(text)
    return tmp

def connect_jdbc_hint():
    print("Prefer JDBC import if thin+pem fails")

def parse_val(v):
    if v is None:
        return None
    return v

def main():
    import oracledb
    data = json.load(open(DUMP, encoding="utf-8"))
    tables = data["tables"]
    wallet = prepare_wallet()
    try:
        os.environ["TNS_ADMIN"] = wallet
        # wallet_password often equals ATP admin pwd when wallet was downloaded
        wp = os.environ.get("ATP_WALLET_PASSWORD", "")
        kwargs = dict(user=USER, password=PASSWORD, dsn=DSN, config_dir=wallet, wallet_location=wallet)
        if wp:
            kwargs["wallet_password"] = wp
        try:
            conn = oracledb.connect(**kwargs)
        except Exception as e:
            print("Connect failed:", e)
            print("Use ImportPlJson.java / JDBC instead")
            raise
        cur = conn.cursor()
        # discover order: known first, then rest
        names = list(ORDER)
        for t in tables:
            if t not in names:
                names.append(t)
        # identity override
        for t in names:
            if t not in tables:
                continue
            try:
                cur.execute(f'ALTER TABLE "{t}" MODIFY ID GENERATED BY DEFAULT AS IDENTITY')
                print("identity default:", t)
            except Exception as e:
                print("identity skip", t, e)
        conn.commit()
        # delete children first
        for t in reversed(names):
            if t not in tables:
                continue
            try:
                cur.execute(f'DELETE FROM "{t}"')
                print("deleted", t, cur.rowcount)
            except Exception as e:
                print("delete skip", t, e)
        conn.commit()
        for t in names:
            if t not in tables:
                continue
            meta = tables[t]
            cols = meta["columns"]
            rows = meta["rows"]
            if not rows:
                print(t, "0 rows")
                continue
            col_list = ",".join(f'"{c}"' for c in cols)
            binds = ",".join(f":{i+1}" for i in range(len(cols)))
            sql = f'INSERT INTO "{t}" ({col_list}) VALUES ({binds})'
            batch = []
            for r in rows:
                batch.append(tuple(parse_val(r.get(c)) for c in cols))
            cur.executemany(sql, batch)
            print(f"inserted {t}: {len(batch)}")
            conn.commit()
        # sync identity
        for t in names:
            if t not in tables:
                continue
            try:
                cur.execute(f'ALTER TABLE "{t}" MODIFY ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)')
                print("identity sync:", t)
            except Exception as e:
                print("identity sync skip", t, e)
        conn.commit()
        print("=== COUNTS ===")
        for t in names:
            if t not in tables:
                continue
            cur.execute(f'SELECT COUNT(*) FROM "{t}"')
            print(f"{t}|{cur.fetchone()[0]}")
        cur.close(); conn.close(); print("DONE")
    finally:
        shutil.rmtree(wallet, ignore_errors=True)

if __name__ == "__main__":
    main()
