import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import java.io.*;
import java.math.BigDecimal;
import java.sql.*;
import java.time.*;
import java.util.*;

public class ImportPlJson {
  static final String[] ORDER = {
    "PRODUCTOS","PERSONAS","CAJA_CONFIG","MARGEN_CONFIG",
    "ENTRADAS","PRODUCCIONES","VENTAS","APARTADOS",
    "TRASPASOS","TRASPASO_LINEAS","TRASPASO_ABONOS",
    "MOVIMIENTOS_CAJA","CORTES_CAJA","INVERSION_ITEMS","PRECIOS_HISTORICOS"
  };

  public static void main(String[] args) throws Exception {
    String dumpPath = args.length > 0 ? args[0] : "/home/opc/productos-limpieza/_migrate/full_dump.json";
    String url = System.getenv().getOrDefault("SPRING_DATASOURCE_URL", "jdbc:oracle:thin:@cgatodb_tp");
    String user = System.getenv().getOrDefault("SPRING_DATASOURCE_USERNAME", "productos_limpieza");
    String pass = System.getenv("SPRING_DATASOURCE_PASSWORD");
    if (pass == null || pass.isEmpty()) throw new IllegalStateException("SPRING_DATASOURCE_PASSWORD missing");

    ObjectMapper om = new ObjectMapper();
    JsonNode root = om.readTree(new File(dumpPath));
    JsonNode tables = root.get("tables");

    Properties props = new Properties();
    props.setProperty("user", user);
    props.setProperty("password", pass);
    System.out.println("Connecting " + url + " as " + user);
    try (Connection conn = DriverManager.getConnection(url, props)) {
      conn.setAutoCommit(false);
      List<String> names = new ArrayList<>();
      for (String t : ORDER) names.add(t);
      tables.fieldNames().forEachRemaining(n -> { if (!names.contains(n)) names.add(n); });

      for (String t : names) {
        if (!tables.has(t)) continue;
        try (Statement st = conn.createStatement()) {
          st.execute("ALTER TABLE \"" + t + "\" MODIFY ID GENERATED BY DEFAULT AS IDENTITY");
          System.out.println("identity default: " + t);
        } catch (SQLException e) {
          System.out.println("identity skip " + t + " " + e.getMessage());
        }
      }
      conn.commit();

      ListIterator<String> it = names.listIterator(names.size());
      while (it.hasPrevious()) {
        String t = it.previous();
        if (!tables.has(t)) continue;
        try (Statement st = conn.createStatement()) {
          int n = st.executeUpdate("DELETE FROM \"" + t + "\"");
          System.out.println("deleted " + t + " " + n);
        } catch (SQLException e) {
          System.out.println("delete skip " + t + " " + e.getMessage());
        }
      }
      conn.commit();

      for (String t : names) {
        if (!tables.has(t)) continue;
        JsonNode meta = tables.get(t);
        ArrayNode colsNode = (ArrayNode) meta.get("columns");
        ArrayNode rows = (ArrayNode) meta.get("rows");
        List<String> cols = new ArrayList<>();
        colsNode.forEach(c -> cols.add(c.asText()));
        if (rows.size() == 0) { System.out.println(t + " 0 rows"); continue; }
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO \"").append(t).append("\" (");
        for (int i = 0; i < cols.size(); i++) {
          if (i > 0) sb.append(",");
          sb.append("\"").append(cols.get(i)).append("\"");
        }
        sb.append(") VALUES (");
        for (int i = 0; i < cols.size(); i++) {
          if (i > 0) sb.append(",");
          sb.append("?");
        }
        sb.append(")");
        try (PreparedStatement ps = conn.prepareStatement(sb.toString())) {
          for (JsonNode row : rows) {
            for (int i = 0; i < cols.size(); i++) {
              JsonNode v = row.get(cols.get(i));
              setParam(ps, i + 1, v);
            }
            ps.addBatch();
          }
          int[] r = ps.executeBatch();
          System.out.println("inserted " + t + ": " + r.length);
        }
        conn.commit();
      }

      for (String t : names) {
        if (!tables.has(t)) continue;
        try (Statement st = conn.createStatement()) {
          st.execute("ALTER TABLE \"" + t + "\" MODIFY ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)");
          System.out.println("identity sync: " + t);
        } catch (SQLException e) {
          System.out.println("identity sync skip " + t + " " + e.getMessage());
        }
      }
      conn.commit();

      System.out.println("=== COUNTS ===");
      try (Statement st = conn.createStatement()) {
        for (String t : names) {
          if (!tables.has(t)) continue;
          try (ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM \"" + t + "\"")) {
            rs.next();
            System.out.println(t + "|" + rs.getInt(1));
          }
        }
      }
      System.out.println("DONE");
    }
  }

  static void setParam(PreparedStatement ps, int idx, JsonNode v) throws SQLException {
    if (v == null || v.isNull()) { ps.setObject(idx, null); return; }
    if (v.isIntegralNumber()) { ps.setLong(idx, v.longValue()); return; }
    if (v.isFloatingPointNumber() || v.isBigDecimal()) { ps.setBigDecimal(idx, v.decimalValue()); return; }
    if (v.isBoolean()) { ps.setInt(idx, v.booleanValue() ? 1 : 0); return; }
    String s = v.asText();
    // ISO date/datetime
    if (s.length() >= 10 && s.charAt(4) == '-' && s.charAt(7) == '-') {
      try {
        if (s.length() > 10) {
          String norm = s.replace("T", " ");
          if (norm.endsWith("Z")) norm = norm.substring(0, norm.length()-1);
          if (norm.contains(".")) norm = norm.substring(0, norm.indexOf('.'));
          ps.setTimestamp(idx, Timestamp.valueOf(LocalDateTime.parse(norm.replace(" ", "T"))));
        } else {
          ps.setDate(idx, java.sql.Date.valueOf(LocalDate.parse(s.substring(0,10))));
        }
        return;
      } catch (Exception ignore) {}
    }
    ps.setString(idx, s);
  }
}
