#!/usr/bin/env python3
"""Import cloud_dump.json into local Oracle (replace all tables)."""
import json
import os
import datetime
import oracledb

dump_path = "/in/cloud_dump.json"
user = os.environ["PL_USER"]
password = os.environ["PL_PASS"]
dsn = os.environ["PL_DSN"]

ORDER = [
    "PRODUCTOS",
    "PERSONAS",
    "CAJA_CONFIG",
    "MARGEN_CONFIG",
    "PEDIDOS",
    "PEDIDO_ITEMS",
    "ENTRADAS",
    "PRODUCCIONES",
    "VENTAS",
    "APARTADOS",
    "TRASPASOS",
    "TRASPASO_LINEAS",
    "TRASPASO_ABONOS",
    "MOVIMIENTOS_CAJA",
    "CORTES_CAJA",
    "INVERSION_ITEMS",
    "PRECIOS_HISTORICOS",
    "AJUSTES_INVENTARIO",
]

with open(dump_path, encoding="utf-8") as f:
    dump = json.load(f)

tables = dump.get("tables", {})
names = list(ORDER)
for t in tables:
    if t not in names:
        names.append(t)

conn = oracledb.connect(user=user, password=password, dsn=dsn)
cur = conn.cursor()


def parse_val(v):
    if v is None:
        return None
    if isinstance(v, str) and len(v) >= 10 and v[4] == "-" and "T" in v:
        try:
            return datetime.datetime.fromisoformat(v.replace("Z", "+00:00")).replace(tzinfo=None)
        except Exception:
            pass
    if isinstance(v, str) and len(v) == 10 and v[4] == "-":
        try:
            return datetime.date.fromisoformat(v)
        except Exception:
            pass
    return v


for t in names:
    if t not in tables:
        continue
    try:
        cur.execute(f'ALTER TABLE "{t}" MODIFY ID GENERATED BY DEFAULT AS IDENTITY')
    except Exception:
        pass
conn.commit()

for t in reversed(names):
    if t not in tables:
        continue
    cur.execute(f'DELETE FROM "{t}"')
    print(f"deleted {t}: {cur.rowcount}")
conn.commit()

total = 0
for t in names:
    if t not in tables:
        continue
    meta = tables[t]
    cols = meta["columns"]
    rows = meta["rows"]
    if not rows:
        print(f"{t}: 0")
        continue
    placeholders = ",".join([f":{i+1}" for i in range(len(cols))])
    col_list = ",".join([f'"{c}"' for c in cols])
    sql = f'INSERT INTO "{t}" ({col_list}) VALUES ({placeholders})'
    ok = 0
    for row in rows:
        vals = [parse_val(row.get(c)) for c in cols]
        try:
            cur.execute(sql, vals)
            ok += 1
        except Exception as e:
            print("ERR", t, str(e)[:200])
    conn.commit()
    try:
        cur.execute(f'ALTER TABLE "{t}" MODIFY ID GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)')
    except Exception:
        pass
    conn.commit()
    print(f"{t}: {ok}/{len(rows)}")
    total += ok

print("TOTAL_OK", total)
print("=== COUNTS ===")
for t in names:
    if t not in tables:
        continue
    cur.execute(f'SELECT COUNT(*) FROM "{t}"')
    print(f"{t}|{cur.fetchone()[0]}")
conn.close()
